repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.7"
    hooks:
      - id: ruff
        language_version: python3
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.22.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]