name: Create tags for changed integrations

on:
  push:
    branches:
      - main

jobs:
  create-integrations-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && pip install packaging

      - name: Describe tags
        id: describe-tags
        run: echo "tags=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Push tags for changed integrations
        env:
          PREVIOUS_TAG: ${{ steps.describe-tags.outputs.tags }}
          CURRENT_COMMIT: ${{ github.sha }}
        run: python scripts/create_tags_for_changed_collections.py