name: Create tags for changed integrations

on:
  push:
    branches:
      - main

jobs:
  create-integrations-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && pip install packaging

      - name: Describe tags
        id: describe-tags
        run: echo "tags=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Get changed integrations
        id: get-changed-integrations
        env:
          PREVIOUS_TAG: ${{ steps.describe-tags.outputs.tags }}
          CURRENT_COMMIT: ${{ github.sha }}
        run: echo "changed_integrations=$(python scripts/get_changed_integrations.py)" >> $GITHUB_OUTPUT

      - name: Create tags
        env:
          CHANGED_INTEGRATIONS: ${{ steps.get-changed-integrations.outputs.changed_integrations }}
        run: |
          echo $CHANGED_INTEGRATIONS | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r name version; do
            tag_name="${name}_v${version}"
            git tag $tag_name
            git push origin $tag_name
          done