name: Get Changed Integrations

on:
  push:
    branches:
      - main

jobs:
  get-changed-integrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Describe tags
        id: describe-tags
        run: echo "tags=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Get changed integrations
        id: get-changed-integrations
        env:
          PREVIOUS_TAG: ${{ steps.describe-tags.outputs.tags }}
          CURRENT_COMMIT: ${{ github.sha }}
        run: echo "changed_integrations=$(python scripts/get_changed_integrations.py)" >> $GITHUB_OUTPUT

      - name: Print the comma delimited integrations one at a time
        env:
          CHANGED_INTEGRATIONS: ${{ steps.get-changed-integrations.outputs.changed_integrations }}
        run: |
          for integration in $(echo $CHANGED_INTEGRATIONS | tr "," "\n")
          do
            echo $integration
          done