name: Get Changed Integrations

on:
  push:
    branches:
      - main

jobs:
  get-changed-integrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Get changed integrations
        run: |
          previous_tag=$(git describe --tags --abbrev=0 HEAD^)
          current_commit=$(git rev-parse HEAD)
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV
          echo "CURRENT_COMMIT=$current_commit" >> $GITHUB_ENV
          python scripts/get_changed_integrations.py