name: Get Changed Integrations

on:
  push:
    branches:
      - main

jobs:
  get-changed-integrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Describe tags
        id: describe-tags
        run: echo ::set-output name=stdout::$(git describe --tags --abbrev=0)

      - name: Get changed integrations
        env:
          PREVIOUS_TAG: ${{ steps.describe-tags.outputs.stdout }}
          CURRENT_COMMIT: ${{ github.sha }}
        run: python scripts/get_changed_integrations.py